### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kolozsvariakos** [vitr/actions-build-and-upload-to-ecs#5]
I would like to use this action, but the latest release is old and not working. I think its preferable to use a specific release in workflows than using the master branch, in case you make a breaking change in the future, it will not brake existing workflows.

**Comment by vitr** [comment]
I've released v1.1.0 if you need it. However, AWS now offers official GitHub Actions at https://github.com/aws-actions. You might want to check them out, as my version could already be outdated.
